# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-24 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeBase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='首次添加时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instance',
            name='from_scan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='from_spider',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='isp',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='organization',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='dev2vul',
            name='device',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dev2vul',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dev2vul',
            name='vulnerability',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='deviceType',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='vendor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='app',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='asn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='banner',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='continent',
            field=models.CharField(max_length=255, null=True, verbose_name='洲'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='extrainfo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='hostname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='ins_type',
            field=models.CharField(max_length=255, null=True, verbose_name='协议'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='ip',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='lat',
            field=models.CharField(max_length=255, null=True, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='lon',
            field=models.CharField(max_length=255, null=True, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='instance',
            name='os',
            field=models.CharField(max_length=255, null=True, verbose_name='操作系统类型'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='port',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='service',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='timestamp',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='type_index',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='vendor',
            field=models.CharField(max_length=255, null=True, verbose_name='厂商'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='version',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='level',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='mitigation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='provider',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='vendor',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
