# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-16 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='authLevel',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.IntegerField(max_length=20),
        ),
    ]
