# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-20 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tests', '0003_auto_20170416_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='authLevel',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.IntegerField(null=True),
        ),
    ]
